name: Sample Kutomize App Deployment

on:
  push:
    branches: [ "master" ]  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script

      - name: Install ArgoCD CLI
        run: |
          curl -sSL -o /usr/local/bin/argocd https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
          chmod +x /usr/local/bin/argocd

      - name: Login to ArgoCD Server
        run: argocd login --username ${{ secrets.ARGOCD_USERNAME }} --password ${{ secrets.ARGOCD_PASSWORD }} --server ${{ secrets.ARGOCD_SERVER }} --insecure

      - name: Create ArgoCD Application
        run: argocd app create webapp-kustom-prod --repo https://github.com/KushNeupane/argo-examples.git --path kustom-webapp/overlays/prod --dest-server https://kubernetes.default.svc --dest-namespace prod